name: Python application

on:
  # push:
  #   branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false  # Disable automatic credential persisting
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Clean Data File
      run: |
        python econ8320-semester-project.py

    - name: Set Git user name and email
      run: |
        git config --global user.name "khem"
        git config --global user.email "khemkandel@gmail.com"


    # Add your files here and commit them
    - name: Commit changes
      run: |
        git add database_clean_latest.xlsx  database_original_latest.xlsx  # Add specific files you want to commit
        git commit -m "Automated update from GitHub Actions"
        git push origin main  # Push to the main branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically used by GitHub Actions