name: processHopeFoundationDatabase

on:
  push:
    branches: main
    paths:
      - 'UNO Service Learning Data Sheet De-Identified Version.xlsx'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true  # Disable automatic credential persisting
        token: ${{ secrets.PAT_ECON_8320 }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Clean Data File
      run: |
        python econ8320-semester-project.py

    - name: Set Git user name and email
      run: |
        git config --global user.name ${{ vars.GIT_CONFIG_USERNAME }}
        git config --global user.email ${{ vars.GIT_CONFIG_EMAIL }}


    # Add your files here and commit them
    - name: Commit changes
      run: |
        git add database_clean_latest.xlsx  database_original_latest.xlsx  # Add specific files you want to commit
        git commit -m "Automated update from GitHub Actions"
        git push origin main  # Push to the main branch
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_ECON_8320 }}  # Automatically used by GitHub Actions


    - name: List matching files
      run: ls -la database_*_latest.xlsx || echo "No files found"

    - name: Upload matching Excel files
      uses: actions/upload-artifact@v4
      with:
        name: clean-data-hopefoundation
        path: database_*_latest.xlsx